# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Golf North Hills
course: Golf North Hills
booking: https://app.easyteegolf.com/course/golf-north-hills/?p=yes
email: kcraft1951@gmail.com
phone: 8709351880
description: >- # this means to ignore newlines until "baseurl:"
  Golf North Hills, a public 9 hole course designed by Booney Harper, and built by Jerry B. Craft, is located 8 miles north of Jonesboro on Hwy 141.
# baseurl: "/"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "//golfnorthhills.com/" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: ""
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_url: "https://www.facebook.com/p/golf-north-hills-100063531704549/"

# Build settings
# theme: minima
permalink: /articles/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate

# paginate: 6
# paginate_path: "/articles/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
